import { chmodSync, existsSync, mkdirSync, readFileSync, realpathSync, rmSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { noelleHome } from "../config.js";
import { hostDir } from "./autostart.js";
import { run } from "./platform.js";
import { launchAgentPath, renderHostLauncher, renderHostPlist, shellQuote } from "./host-launch.js";

/**
 * macOS periodic auto-update (host-side). A StartInterval LaunchAgent runs
 * `noelle sync` every N minutes (and once at load): the Mac fast-forwards the
 * tracked branch, builds, and rsyncs into the VM. Separate from the login
 * autostart agent so the two can be toggled independently.
 */

export const LABEL = "com.noelle.autoupdate";

export function launcherPath(): string {
  return resolve(hostDir(), "autoupdate.sh");
}
export function logPath(): string {
  return resolve(hostDir(), "autoupdate.log");
}
export function plistPath(): string {
  return launchAgentPath(LABEL);
}

export interface LauncherInputs {
  nodeBin: string;
  cliEntry: string;
  pathDirs: string[];
  home?: string;
}

/** The periodic launcher script (pure — snapshot-tested). */
export function renderLauncher(i: LauncherInputs): string {
  return renderHostLauncher({ ...i, args: ["sync"] });
}

export interface PlistInputs {
  label: string;
  launcher: string;
  log: string;
  intervalSeconds: number;
}

/**
 * The StartInterval LaunchAgent plist (pure — snapshot-tested). ProcessType
 * must NOT be Background: the clamp inherits into anything this job spawns —
 * if a sync tick finds the pm2 daemon dead and revives it, a Background type
 * would pin the entire runtime to background QoS until the next reboot.
 */
export function renderPlist(i: PlistInputs): string {
  return renderHostPlist({ ...i, processType: "Standard" });
}

/** A git post-commit hook that kicks a native `noelle sync` (background, non-blocking). */
export function renderPostCommitHook(i: {
  nodeBin: string;
  cliEntry: string;
  repoRoot: string;
  home?: string;
}): string {
  return `#!/bin/bash
# noelle-managed post-commit hook. Generated by \`noelle autoupdate install\` (native).
# A commit rebuilds the workers immediately instead of waiting for the launchd tick.
#
# Git exports GIT_DIR (and friends) to hooks, and hooks fire for COMMITS IN
# WORKTREES too. Scrub that context before syncing the runtime checkout.
# Only a commit in the runtime checkout may deploy.
unset GIT_DIR GIT_WORK_TREE GIT_INDEX_FILE
top="$(git rev-parse --show-toplevel 2>/dev/null)"
[ "$top" = ${shellQuote(i.repoRoot)} ] || exit 0
${i.home ? `export NOELLE_HOME=${shellQuote(i.home)}\n` : ""}
( ${shellQuote(i.nodeBin)} ${shellQuote(i.cliEntry)} sync >/dev/null 2>&1 & )
`;
}

/**
 * Write the post-commit hook (native deploy) unless a non-Noelle hook already
 * occupies the slot. Idempotent: it overwrites its own previous managed hook but
 * never clobbers a hook the operator wrote by hand.
 */
export function installPostCommitHook(
  repoRoot: string,
  i: { nodeBin: string; cliEntry: string },
): void {
  const hookPath = resolve(repoRoot, ".git", "hooks", "post-commit");
  if (existsSync(hookPath)) {
    const cur = readFileSync(hookPath, "utf8");
    if (!cur.includes("noelle-managed")) return; // respect a user's own hook
  }
  writeFileSync(hookPath, renderPostCommitHook({ ...i, repoRoot: realpathSync(repoRoot), home: noelleHome() }), { mode: 0o755 });
  chmodSync(hookPath, 0o755);
}

function guiDomain(): string {
  return `gui/${process.getuid?.() ?? 501}`;
}

export interface InstallInputs {
  repoRoot: string;
  nodeBin: string;
  pathDirs: string[];
  intervalMinutes: number;
}

export async function install(i: InstallInputs): Promise<void> {
  mkdirSync(hostDir(), { recursive: true });
  mkdirSync(resolve(plistPath(), ".."), { recursive: true });

  const launcher = renderLauncher({
    nodeBin: i.nodeBin,
    cliEntry: resolve(i.repoRoot, "apps/cli/dist/index.js"),
    pathDirs: i.pathDirs,
    home: noelleHome(),
  });
  writeFileSync(launcherPath(), launcher, { mode: 0o755 });
  chmodSync(launcherPath(), 0o755);

  writeFileSync(
    plistPath(),
    renderPlist({
      label: LABEL,
      launcher: launcherPath(),
      log: logPath(),
      intervalSeconds: Math.max(60, Math.round(i.intervalMinutes * 60)),
    }),
    { mode: 0o644 },
  );

  await run("launchctl", ["bootout", `${guiDomain()}/${LABEL}`], { allowFailure: true });
  await run("launchctl", ["bootstrap", guiDomain(), plistPath()], { inherit: true });
}

export async function uninstall(): Promise<void> {
  await run("launchctl", ["bootout", `${guiDomain()}/${LABEL}`], { allowFailure: true });
  if (existsSync(plistPath())) rmSync(plistPath());
}

export async function isLoaded(): Promise<boolean> {
  const r = await run("launchctl", ["print", `${guiDomain()}/${LABEL}`], { allowFailure: true });
  return r.code === 0;
}

export interface AutoUpdateStatus {
  loaded: boolean;
  plist: string;
  plistExists: boolean;
  lastLog: string | null;
}

export async function status(): Promise<AutoUpdateStatus> {
  const plist = plistPath();
  let lastLog: string | null = null;
  if (existsSync(logPath())) {
    const lines = readFileSync(logPath(), "utf8").trim().split("\n");
    lastLog = lines.slice(-10).join("\n") || null;
  }
  return { loaded: await isLoaded(), plist, plistExists: existsSync(plist), lastLog };
}
