import { writeFileSync } from "node:fs";
import { resolve, relative, isAbsolute } from "node:path";
import { SERVICES, WORKER_SERVICES, MANAGED_PROCESS_NAMES } from "./service-manifest.js";
import type { SelfHostConfig } from "../config.js";
import type { Paths } from "../config.js";
import { run, type RunResult } from "./platform.js";
import { envParsingSource } from "./env-writer.js";

/**
 * pm2 orchestration. pm2 is the default cross-platform process manager (one
 * ecosystem file works identically on macOS + Linux). The generated
 * ecosystem.config.cjs parses the shared .env itself and merges it into each
 * app's env, so secrets live only in .env (0600), never in the ecosystem file.
 *
 * Workers (discovery/classifier/drafter/send) and the spend-rollup are defined
 * but `autostart:false` unless workers are enabled — v1 ships dashboard + API.
 */

export function generateEcosystem(args: {
  config: SelfHostConfig;
  repoRoot: string;
  paths: Paths;
}): string {
  const { config, repoRoot, paths } = args;
  const workers = config.workersEnabled;
  // Both runtimes serve the prod build (`next start`). Native briefly ran
  // `next dev` (live on save), but a dev server ships ~14 MB of unminified JS
  // per page and compiles routes on demand — the dashboard felt broken (dead
  // buttons until hydration, multi-second navigations). `noelle up` / `noelle
  // sync` build the app, so `next start` always has a fresh .next to serve.
  const appArgs = "--filter @noelle/app start";
  // The ecosystem is plain CJS executed by pm2; it reads .env at load.
  return `// Generated by \`noelle init\`. Edit via the CLI, not by hand.
const fs = require("fs");

${envParsingSource()}

const ENV_FILE = ${JSON.stringify(paths.envFile)};
const ENV = fs.existsSync(ENV_FILE) ? parseEnvText(fs.readFileSync(ENV_FILE, "utf8")) : {};
const REPO = ${JSON.stringify(repoRoot)};
const LOGS = ${JSON.stringify(paths.logs)};

function app(name, extra) {
  return Object.assign(
    {
      name,
      cwd: REPO,
      autorestart: true,
      max_restarts: 10,
      out_file: LOGS + "/" + name + ".out.log",
      error_file: LOGS + "/" + name + ".err.log",
      merge_logs: true,
    },
    extra,
  );
}

function worker(name, appDir, kind, autostart) {
  return app(name, {
    script: "./run.sh", args: kind, interpreter: "bash",
    cwd: REPO + "/apps/" + appDir, autostart,
    env: Object.assign({}, ENV),
  });
}

module.exports = {
  apps: [
    app(${JSON.stringify(SERVICES.api)}, {
      script: "pnpm",
      args: "--filter @noelle/api-vm start",
      env: Object.assign({}, ENV, { PORT: ${JSON.stringify(String(config.ports.apiVm))} }),
    }),
    app(${JSON.stringify(SERVICES.app)}, {
      script: "pnpm",
      args: ${JSON.stringify(appArgs)},
      env: Object.assign({}, ENV, { PORT: ${JSON.stringify(String(config.ports.app))} }),
    }),
    ${WORKER_SERVICES.map((worker) => `worker(${JSON.stringify(worker.name)}, ${JSON.stringify(worker.app)}, ${JSON.stringify(worker.kind)}, ${workers && worker.autonomous}),`).join("\n    ")}
    // Spend rollup: aggregates llm_calls → org_spend_month every 5 min so the
    // nav-pill / billing figures match live spend (replaces the Vercel cron).
    // Always on (cheap; keeps the budget UI correct even dashboard-only).
    app(${JSON.stringify(SERVICES.spend)}, {
      script: "node",
      args: "apps/cli/dist/index.js rollup --watch",
      env: Object.assign({}, ENV),
      autostart: true,
    }),
    // Chrome Bridge + Actuator Doctor (self-healing
    // watchdog). Standalone infra like api-vm/app/spend-rollup — always on,
    // NOT gated on workersEnabled and NEVER touching the actuator send path.
    // Each execs its own run.sh (picks a node, execs dist/index.js). Port + token
    // come from the shared ENV (NOELLE_BRIDGE_PORT/NOELLE_BRIDGE_TOKEN); the app
    // reads process.env, so no extra plumbing here.
    //
    // NOTE: 'noelle sync' never regenerates this file or starts NEW apps, so on
    // first deploy the operator runs 'noelle bridge start' / 'noelle doctor
    // start' (or 'noelle up') once to launch these; later restarts are
    // deploy-driven like every other app.
    app(${JSON.stringify(SERVICES.bridge)}, {
      script: "./run.sh",
      interpreter: "bash",
      cwd: REPO + "/apps/chrome-bridge",
      autostart: true,
      env: Object.assign({}, ENV),
    }),
    app(${JSON.stringify(SERVICES.doctor)}, {
      script: "./run.sh",
      interpreter: "bash",
      cwd: REPO + "/apps/actuator-doctor",
      autostart: true,
      env: Object.assign({}, ENV),
    }),
  ],
};
`;
}

/**
 * Pure: recover the repo root a generated ecosystem file was written for (the
 * `const REPO = "...";` line). The deploy loop refuses to build any other
 * checkout: restarting the shared pm2 fleet from a worktree would stamp
 * lastBuiltSha with a sha the runtime checkout never built.
 */
export function ecosystemRepoRoot(source: string): string | null {
  const m = source.match(/^const REPO = ("(?:[^"\\]|\\.)*");$/m);
  if (!m || !m[1]) return null;
  try {
    const parsed: unknown = JSON.parse(m[1]);
    return typeof parsed === "string" && parsed.length > 0 ? parsed : null;
  } catch {
    return null;
  }
}

export function writeEcosystem(args: {
  config: SelfHostConfig;
  repoRoot: string;
  paths: Paths;
}): void {
  const content = generateEcosystem(args);
  writeFileSync(args.paths.ecosystem, content, { mode: 0o644 });
}

// Invoke pm2 through the @noelle/cli package so pnpm resolves its bundled
// binary. pm2 is a dependency of @noelle/cli, not the workspace root, so a
// plain `pnpm exec pm2` from repoRoot fails with "Command pm2 not found"
// (pnpm doesn't hoist it to the root .bin). `--filter @noelle/cli exec` runs
// in that package's context where pm2 IS on the bin path.
const PM2_BASE = ["--filter", "@noelle/cli", "exec", "pm2"];

/** Invoke pm2 via pnpm, resolving the @noelle/cli-bundled binary. */
function pm2(repoRoot: string, args: string[], allowFailure = false): Promise<RunResult> {
  return run("pnpm", [...PM2_BASE, ...args], { cwd: repoRoot, allowFailure });
}

export async function pm2Start(repoRoot: string, ecosystemPath: string): Promise<void> {
  await pm2(repoRoot, ["start", ecosystemPath, "--update-env"]);
}

/**
 * Restart a specific pm2 app so it picks up a fresh build. `pm2 start` is a
 * no-op on an already-online process, and `next start` reads `.next` only at
 * boot — so without this an `up --build` rebuilds but keeps serving the old
 * bundle. A failed restart is returned to the caller.
 */
export async function pm2Restart(repoRoot: string, name: string): Promise<void> {
  await pm2(repoRoot, ["restart", name, "--update-env"]);
}

/** Restart selected services through the ecosystem so its current .env is read.
 * Returns the actual process result; an empty list performs no restart. */
export async function pm2RestartMany(
  repoRoot: string,
  names: string[],
  ecosystemPath?: string,
): Promise<RunResult | null> {
  if (names.length === 0) return null;
  if (ecosystemPath) {
    return pm2(repoRoot, ["restart", ecosystemPath, "--only", names.join(","), "--update-env"], true);
  }
  return pm2(repoRoot, ["restart", ...names, "--update-env"], true);
}

export async function pm2StartApp(repoRoot: string, ecosystemPath: string, name: string): Promise<void> {
  await pm2(repoRoot, ["start", ecosystemPath, "--only", name, "--update-env"]);
}

/**
 * Restart one app RE-EVALUATING the ecosystem file. A name-based `pm2 restart
 * <name> --update-env` reuses the env the daemon captured at first start;
 * restarting via the ecosystem path re-parses it (and thus a refreshed .env,
 * e.g. a re-minted operator JWT). A failed restart rejects.
 */
export async function pm2RestartFromEcosystem(
  repoRoot: string,
  ecosystemPath: string,
  name: string,
): Promise<void> {
  await pm2(repoRoot, ["restart", ecosystemPath, "--only", name, "--update-env"]);
}

export async function pm2Stop(repoRoot: string, remove: boolean): Promise<void> {
  const targets = (await pm2Status(repoRoot)).filter((process) => ownsProcess(process, repoRoot)).map((process) => process.name);
  if (targets.length) await pm2(repoRoot, [remove ? "delete" : "stop", ...targets]);
}

export async function pm2Logs(repoRoot: string, service?: string): Promise<void> {
  const args = ["logs", "--lines", "80"];
  if (service) args.splice(1, 0, service);
  await run("pnpm", [...PM2_BASE, ...args], { cwd: repoRoot, inherit: true, allowFailure: true });
}

/**
 * One-shot log dump for a single pm2 app (`--nostream`): print the last N lines
 * and return, rather than tailing forever like `pm2Logs`. Backs `noelle bridge
 * logs` / `noelle doctor logs`. No-op-safe (allowFailure) if the app isn't
 * registered yet.
 */
export async function pm2LogsOnce(repoRoot: string, name: string, lines: number): Promise<void> {
  await run("pnpm", [...PM2_BASE, "logs", name, "--lines", String(lines), "--nostream"], {
    cwd: repoRoot,
    inherit: true,
    allowFailure: true,
  });
}

export interface Pm2Process {
  name: string;
  status: string;
  restarts: number;
  cpu: number;
  memoryMb: number;
  cwd?: string;
}

function ownsProcess(process: Pm2Process, repoRoot: string): boolean {
  if (!MANAGED_PROCESS_NAMES.has(process.name) || !process.cwd) return false;
  const path = relative(resolve(repoRoot), resolve(process.cwd));
  return path === "" || (!isAbsolute(path) && path.startsWith("apps/") && !path.split("/").includes(".."));
}

export function pm2DeployRestartTargets(procs: Pm2Process[], repoRoot: string): string[] {
  return procs.filter((process) => process.status !== "stopped" && ownsProcess(process, repoRoot)).map((process) => process.name);
}

/** Parse `pm2 jlist` into a tidy status array; [] if pm2 has no processes. */
export async function pm2Status(repoRoot: string): Promise<Pm2Process[]> {
  const r = await pm2(repoRoot, ["jlist"], true);
  if (r.code !== 0) throw new Error("Process manager status query failed");
  try {
    const list = JSON.parse(r.stdout) as Array<{
      name?: string;
      pm2_env?: { status?: string; restart_time?: number; pm_cwd?: string };
      monit?: { cpu?: number; memory?: number };
    }>;
    if (!Array.isArray(list) || list.some((p) => !p || typeof p.name !== "string" || !p.name.trim()))
      throw new Error("Invalid process manager status receipt");
    return list.map((p) => ({
      name: p.name ?? "?",
      status: p.pm2_env?.status ?? "unknown",
      cwd: typeof p.pm2_env?.pm_cwd === "string" ? p.pm2_env.pm_cwd : undefined,
      restarts: p.pm2_env?.restart_time ?? 0,
      cpu: p.monit?.cpu ?? 0,
      memoryMb: Math.round((p.monit?.memory ?? 0) / (1024 * 1024)),
    }));
  } catch {
    throw new Error("Invalid process manager status receipt");
  }
}
