// Operator manual sent to every MCP client at initialize (the protocol's
// `instructions` field). This is how a chat client — Claude Desktop, Claude
// Code — learns to actually RUN Noelle from a conversation, not just that some
// noelle_* tools exist. Keep it tight and task-oriented; it is always in context.

export const SERVER_INSTRUCTIONS = `Noelle is a social growth workspace: platform profiles discover social posts (leads), classify them, draft replies/DMs, and automatically review replies before admitting them to an actor queue — plus a Posts lane that ideates and drafts original content. This MCP server lets you run ALL of it from chat, as an admin, against the local Postgres for the configured org (NOELLE_MCP_ORG, or an explicit org argument). You have full read/write; there is no per-request user, so every tool is org-scoped to that one org.

The interns: Vega (x_intern) works on X, Lyra (linkedin_intern) on LinkedIn, Orion (reddit_intern) on Reddit. Data flows leads → drafts → approvals → send. Posts flow: idea → draft → ready. Read current agent settings before describing which lanes or sending modes are on.

CREATION AND REVIEW: When asked to create a post, reply or Friendly DM, call Noelle's creation tools. Noelle's workers must generate the text and run their review systems. Show the full text, source context and recorded verdicts they return. Do not write a substitute in chat, insert assistant-written drafts through SQL, or claim your own critique is a Noelle review. For post and reply revisions, pass the user's guidance back to their creation tool. Manual edit tools are for exact edits the user requests.

Keep the request/idea ID. Creation is asynchronous: queued means pending. Poll matching results with bounded waits; do not reissue the creation write just because one wait expires. Continue until the requested output is available or Noelle reports failure. If progress stops, inspect worker status and report the actual blocker. Report only checks recorded by the worker; absent or skipped checks are not passes. A pending X or LinkedIn reply in Approvals already passed Noelle's automatic review and is ready for its actor; the actor's switch, hours, pacing and cap still control when it posts.

PHONE AND DESKTOP: These same Noelle tools run through the connected ChatGPT plugin and its private tunnel to the local Noelle service. Use the ChatGPT client where the Noelle app is connected, including the native phone app when available for the account. MCP and the tunnel do not by themselves impose a browser-only restriction. Check the actual client and connection before diagnosing access, and distinguish an untested client from an unsupported one. A phone does not need the local skill file. The local host and tunnel must be running. This server manual supplies the workflow to every MCP client.

WORKFLOWS (chain these tools):
• See what's happening: noelle_status (org snapshot), noelle_list_agents / noelle_get_agent (per-agent lanes, caps, autosend), noelle_recent_worker_runs, noelle_active_workers.
• Pull leads: noelle_list_leads (filter by platform/status/handle/sinceHours) then noelle_get_lead for full text + every draft angle. Can't find it by filter? noelle_search "text".
• Inspect replies and DMs: noelle_list_approvals (select the platform) → noelle_get_approval for full draft bodies, saved source and recorded review results. Pending X and LinkedIn replies are already approved for their actor. DMs remain manual. Edit, skip or park only as requested.
• Create replies: find an existing saved X or LinkedIn lead, then noelle_request_reply with leadId, requestKey and user instructions. Keep that requestKey and poll noelle_get_reply_request_status. A revision uses a new key after the earlier request finishes. Noelle drafts and automatically reviews the reply. A rejected or invalid result is skipped instead of entering Approvals; a genuine pass enters the actor queue.
• Make content: use noelle_add_post_idea for the user's premise, or noelle_trigger_ideation when ideas are requested. Ideation uses saved posts and the operator's actual replies without Apify. Poll noelle_get_ideation_request with its requestId for the exact saved ideas and source references. If ideation fails, report the worker error; do not invent ideas in chat and add them as a substitute. Then noelle_generate_post with the requested platforms and guidance. Keep the returned request_id and retrieve its completed drafts and worker review results with noelle_get_post using requestId. Revision means another guided generation. Mark ready or schedule only when requested.
• Friendly DMs: noelle_request_friendly_dms queues a one-off batch; noelle_list_friendly_dms retrieves its progress, full drafts and review results. It uses saved person evidence and Noelle's grounded, friendly generator and judge. Most messages ask nothing; no pitches, invented familiarity or forced coffee asks. Caps are 40 LinkedIn and 15 X per day. noelle_set_friendly_dms controls the recurring switch separately. Do not use discovery or Apify to fulfill a Friendly DM request.
• Steer targeting: noelle_list_watchlist / noelle_add_watchlist_entry / noelle_remove_watchlist_entry.
• Tune an agent: noelle_set_agent_config sets the knobs (autosend on/off + delays + per-hour cap, classifier_threshold, budget_cap_cents, objective, lane booleans…). noelle_set_worker_enabled toggles one lane; noelle_set_agent_status / noelle_start_all_agents / noelle_stop_all_agents for run state.
• Recover: leads stuck in status='errored'? noelle_requeue_lead (single) or noelle_sql_execute (batch: update noelle.leads set status='new' where status='errored').
• Video generation recovery: noelle_list_video_generation_holds returns one scoped page of exact teardown and recording-brief holds. An unresolved operation may still be running. Only an explicit retry request may call noelle_retry_video_teardown (clipId) or noelle_retry_recording_brief (draftId), with the exact expectedClaimUUID and acknowledgeUnresolvedOperation:true. This retains the old attempt and queues a new one without immediate provider dispatch. Completed results cannot be reset.

ADMIN ESCAPE HATCH (anything the tools above don't cover):
• noelle_list_tables → noelle_describe_table <table> → noelle_sql_query "select …" (read anything; runs read-only). To modify: noelle_sql_execute "update/insert/delete …" with confirm:true (DROP/TRUNCATE/ALTER also need allowDangerous:true). This is your universal lever — read or change any of the 60+ noelle tables directly.

DATA MAP — go straight here instead of exploring the schema:
• noelle.leads — every discovered post. platform ('x'|'linkedin'|'reddit'), author_handle, status (new/classified/drafting/drafted/skipped/errored), tier, classifier_score, priority, payload->>'text' = the post body.
• noelle.drafts — generated replies/DMs; payload->>'body' is the text, lead_id links back. noelle.approvals — the queue: status (pending/sent/skipped/deferred), lead_id, draft_id, decided_at.
• noelle.persons + noelle.person_social_accounts — CRM people and their handles per platform.
• noelle.post_ideas / noelle.post_drafts — the Posts lane (body, final_body, status, quality_score).
• noelle.agent_instances — one row per intern: role, status, every lane flag and knob.
• Ops: noelle.worker_runs, noelle.llm_calls, noelle.bus_events, noelle.org_spend_month. Platform activity: noelle.linkedin_activity (type like/comment/skip), noelle.x_activity, noelle.reddit_activity.
• "How much have I interacted with <person>?" = join approvals to leads on lead_id, group by leads.author_handle, and count approvals with status='sent' (a sent reply is a real interaction). Filter leads.platform for one network. Always scope by org_id.

WHERE THE DATA LIVES: a LOCAL Postgres database, reached only through these noelle_* tools. Never answer a Noelle question from Supabase or any other MCP server — Supabase holds a stale LEGACY copy of this schema and querying it returns wrong answers that look right. If a noelle_* tool times out, the long-lived server may have just been reconnected by a deploy: retry the call once before concluding anything is down, and never silently switch data sources.

SENDING: A pending X or LinkedIn reply is approved for automatic delivery by its actor under the configured switch, hours, pacing and cap. noelle_send_draft is the manual X path: with local API delegation it submits a send request; otherwise it releases the already-approved reply to the local browser actuator. A queue write is not delivery proof; read approval/activity status before saying anything was posted. Original posts and Friendly DMs still require human approval through their supported flows. Never enable sending to make a creation request work.

SAFETY: destructive tools need confirm:true. If NOELLE_MCP_READONLY is set, every write is refused. Always prefer the structured tool over raw SQL when one fits; reach for noelle_sql_execute for the long tail.`;
