#!/usr/bin/env bash
# Projects GCP Secret Manager values onto /etc/noelle/*.env files used by the
# api-vm Hono service and the worker pool (discovery / classifier / drafter /
# send). Run on noelle-vm-0 at deploy time. See docs/secrets.md § 4.3 and
# infra/systemd/README.md.
#
# Two files written:
#   /etc/noelle/db.env      — NOELLE_DATABASE_URL composed from
#                             noelle-postgres-app-password
#   /etc/noelle/worker.env  — Non-secret config + HMAC and AI Gateway keys.
#                             Other worker secrets (nella, x cookies, bedrock,
#                             codex auth) are fetched at boot via SecretsClient.
#
# Secret names use hyphens — GCP Secret Manager does not allow `/` in names,
# so the legacy `noelle/worker/foo` paths from the design docs are stored as
# `noelle-worker-foo`. The runtime SecretsClient normalises slashes to dashes,
# but this script talks to gcloud directly and must use the canonical form.
#
# Idempotent: safe to re-run. Atomic writes via mktemp + install.

set -euo pipefail

PROJECT="${PROJECT:-${NOELLE_GCP_PROJECT:-}}"
DB_DEST="${DB_DEST:-/etc/noelle/db.env}"
WORKER_DEST="${WORKER_DEST:-/etc/noelle/worker.env}"
CONFIG_ENV="${NOELLE_CONFIG_ENV_FILE:-/etc/noelle/api-vm.env}"
if [[ -z "$PROJECT" && -f "$CONFIG_ENV" ]]; then
  PROJECT="$(sed -n 's/^GCP_PROJECT=//p' "$CONFIG_ENV" | head -1)"
fi
DB_HOST="${DB_HOST:-}"
if [[ -z "$DB_HOST" && -f "$DB_DEST" ]]; then
  # Read only the hostname from saved configuration; connection credentials stay on stdin.
  DB_HOST="$(sed -n 's/^NOELLE_DATABASE_URL=//p' "$DB_DEST" | head -1 | node -e '
    let value=""; process.stdin.on("data", part => value+=part);
    process.stdin.on("end", () => { try { process.stdout.write(new URL(value.trim()).hostname); } catch {} });
  ')"
fi
[[ -n "$PROJECT" ]] || { echo "Configure PROJECT or NOELLE_GCP_PROJECT for this installation." >&2; exit 2; }
[[ -n "$DB_HOST" ]] || { echo "Configure DB_HOST for this installation." >&2; exit 2; }
DB_NAME="${DB_NAME:-noelle}"
DB_USER="${DB_USER:-noelle_app}"

fetch() {
  gcloud --project="$PROJECT" secrets versions access latest --secret="$1"
}

# URL-encode a string with awk (no jq dependency on the VM).
urlenc() {
  awk -v s="$1" 'BEGIN{
    for (i=0;i<256;i++) chr[sprintf("%c",i)]=sprintf("%%%02X",i);
    out="";
    n=length(s);
    for (i=1;i<=n;i++) {
      c=substr(s,i,1);
      if (c ~ /[A-Za-z0-9._~-]/) out=out c; else out=out chr[c];
    }
    print out;
  }'
}

write_envfile() {
  local dest="$1"
  local owner_group="${2:-root:noelle-api}"
  local mode="${3:-0640}"
  local content="$4"
  local tmp
  tmp="$(mktemp)"
  printf '%s' "$content" > "$tmp"
  install -m "$mode" -o "${owner_group%%:*}" -g "${owner_group##*:}" "$tmp" "$dest"
  rm -f "$tmp"
  echo "wrote $dest"
}

# ---- db.env ---------------------------------------------------------------
DB_PW="$(fetch noelle-postgres-app-password)"
DB_PW_ENC="$(urlenc "$DB_PW")"
DB_URL="postgres://${DB_USER}:${DB_PW_ENC}@${DB_HOST}:5432/${DB_NAME}?sslmode=require"

DB_CONTENT=$(cat <<EOF
# Generated by scripts/pull-secrets.sh — do not edit by hand.
NOELLE_DATABASE_URL=$DB_URL
EOF
)
write_envfile "$DB_DEST" root:noelle-api 0640 "$DB_CONTENT"

# ---- worker.env -----------------------------------------------------------
# Only HMAC is a true secret here. Everything else is non-secret runtime
# config that the worker code (env.ts) reads with zod defaults; we surface
# it explicitly so an operator can override without touching code.
HMAC="$(fetch noelle-worker-hmac-secret)"
GATEWAY_KEY="$(fetch noelle-worker-ai-gateway-api-key 2>/dev/null || true)"
if [[ -n "$GATEWAY_KEY" && ! "$GATEWAY_KEY" =~ ^[A-Za-z0-9_-]+$ ]]; then
  echo "invalid AI Gateway secret format" >&2
  exit 1
fi

WORKER_CONTENT=$(cat <<EOF
# Generated by scripts/pull-secrets.sh — do not edit by hand.
NODE_ENV=production
GCP_PROJECT=$PROJECT
NOELLE_HMAC_SECRET=$HMAC
# Per-tick secrets (nella api key, codex auth.json, x cookies, bedrock keys)
# are fetched via SecretsClient (apps/x-intern/src/lib/secrets.ts), not from
# this file. Add overrides here only when running against a non-default region
# or a non-default Nella deployment.
EOF
)
if [[ -n "$GATEWAY_KEY" ]]; then
  WORKER_CONTENT="${WORKER_CONTENT}"$'\n'"AI_GATEWAY_API_KEY=$GATEWAY_KEY"
else
  echo "AI Gateway secret unavailable; Jev will pause browser discovery" >&2
fi
write_envfile "$WORKER_DEST" root:noelle-api 0640 "$WORKER_CONTENT"

echo "pull-secrets: done."
